export interface FieldSchema {
	name: string
	type: 'string' | 'number' | 'boolean' | 'object' | 'array' | 'file'
	label: string
	defaultValue: string | number | boolean | object | null
	required?: boolean
	description?: string
	fields?: FieldSchema[]
}

export interface StepBodySchema {
	stepId: number | string
	fields: FieldSchema[]
}

export const stepBodySchemas: Record<string, FieldSchema[]> = {
	'create_broadcaster': [
		{
			name: 'companyName',
			type: 'string',
			label: 'Company Name',
			defaultValue: 'My Company',
			required: true,
			description: 'Name of the company',
		},
		{
			name: 'companyAddress',
			type: 'string',
			label: 'Company Address',
			defaultValue: '123 Main Street',
			required: true,
			description: 'Address of the company',
		},
		{
			name: 'contactPerson',
			type: 'string',
			label: 'Contact Person',
			defaultValue: 'John Doe',
			required: true,
			description: 'Name of the contact person',
		},
		{
			name: 'email',
			type: 'string',
			label: 'Email',
			defaultValue: 'contact@example.com',
			required: true,
			description: 'Email address',
		},
		{
			name: 'mobile',
			type: 'string',
			label: 'Mobile',
			defaultValue: '+1234567890',
			required: true,
			description: 'Mobile phone number',
		},
	],
	'add_channel': [
		{
			name: 'name',
			type: 'string',
			label: 'Name',
			defaultValue: 'Channel 1',
			required: true,
		},
		{
			name: 'broadcasterId',
			type: 'number',
			label: 'Broadcaster ID',
			defaultValue: 1,
			required: true,
		},
		{
			name: 'lcn',
			type: 'number',
			label: 'LCN',
			defaultValue: 1,
			required: true,
		},
		{
			name: 'accessCriteria',
			type: 'number',
			label: 'Access Criteria',
			defaultValue: 0,
			required: true,
		},
		{
			name: 'assetId',
			type: 'string',
			label: 'Asset ID',
			defaultValue: 'asset-001',
			required: false,
		},
		{
			name: 'contentType',
			type: 'number',
			label: 'Content Type',
			defaultValue: 0,
			required: true,
		},
		{
			name: 'enableFP',
			type: 'number',
			label: 'Enable FP',
			defaultValue: 0,
			required: true,
		},
		{
			name: 'encrypt',
			type: 'number',
			label: 'Encrypt',
			defaultValue: 0,
			required: true,
		},
		{
			name: 'idOnTranscoder',
			type: 'string',
			label: 'ID on Transcoder',
			defaultValue: '550e8400-e29b-41d4-a716-446655440000',
			required: false,
		},
		{
			name: 'language',
			type: 'number',
			label: 'Language',
			defaultValue: 0,
			required: true,
		},
		{
			name: 'logo',
			type: 'string',
			label: 'Logo',
			defaultValue: 'https://example.com/logo.png',
			required: false,
		},
		{
			name: 'manifestUrl',
			type: 'string',
			label: 'Manifest URL',
			defaultValue: 'https://example.com/manifest.m3u8',
			required: false,
		},
		{
			name: 'multicastUrl',
			type: 'string',
			label: 'Multicast URL',
			defaultValue: 'udp://239.0.0.1:5000',
			required: false,
		},
		{
			name: 'price',
			type: 'number',
			label: 'Price',
			defaultValue: 0,
			required: true,
		},
	],
	'edit_channel': [
		{
			name: 'id',
			type: 'number',
			label: 'Channel ID',
			defaultValue: 1,
			required: true,
		},
		{
			name: 'name',
			type: 'string',
			label: 'Channel Name',
			defaultValue: 'Updated Channel',
			required: false,
		},
	],
	'add_package': [
		{
			name: 'name',
			type: 'string',
			label: 'Package Name',
			defaultValue: 'Premium Package',
			required: true,
		},
		{
			name: 'price',
			type: 'number',
			label: 'Price',
			defaultValue: 99.99,
			required: true,
		},
		{
			name: 'duration',
			type: 'number',
			label: 'Duration (days)',
			defaultValue: 30,
			required: true,
		},
	],
	'add_channel_to_package': [
		{
			name: 'packageId',
			type: 'number',
			label: 'Package ID',
			defaultValue: 1,
			required: true,
		},
		{
			name: 'channelIds',
			type: 'array',
			label: 'Channel IDs',
			defaultValue: [],
			required: true,
		},
	],
	'create_stb_vendor': [
		{
			name: 'id',
			type: 'string',
			label: 'ID',
			defaultValue: 'vendor-001',
			required: true,
		},
		{
			name: 'companyName',
			type: 'string',
			label: 'Company Name',
			defaultValue: 'STB Vendor Company',
			required: true,
		},
		{
			name: 'companyAddress',
			type: 'string',
			label: 'Company Address',
			defaultValue: '123 Vendor Street',
			required: true,
		},
		{
			name: 'contactPerson',
			type: 'string',
			label: 'Contact Person',
			defaultValue: 'John Doe',
			required: true,
		},
		{
			name: 'email',
			type: 'string',
			label: 'Email',
			defaultValue: 'vendor@example.com',
			required: true,
		},
		{
			name: 'mobile',
			type: 'string',
			label: 'Mobile',
			defaultValue: '+1234567890',
			required: true,
		},
	],
	'add_subscriber': [
		{
			name: 'username',
			type: 'string',
			label: 'Username',
			defaultValue: 'subscriber1',
			required: true,
		},
		{
			name: 'email',
			type: 'string',
			label: 'Email',
			defaultValue: 'subscriber@example.com',
			required: true,
		},
		{
			name: 'fullName',
			type: 'string',
			label: 'Full Name',
			defaultValue: 'John Doe',
			required: false,
		},
	],
	'pair_device_to_subscriber': [
		{
			name: 'subscriberId',
			type: 'number',
			label: 'Subscriber ID',
			defaultValue: 1,
			required: true,
		},
		{
			name: 'deviceId',
			type: 'number',
			label: 'Device ID',
			defaultValue: 1,
			required: true,
		},
	],
	'import_devices': [
		{
			name: 'file',
			type: 'file',
			label: 'Excel File',
			defaultValue: null,
			required: true,
			description: 'Upload Excel file to import devices',
		},
	],
	'add_device': [
		{
			name: 'id',
			type: 'string',
			label: 'ID',
			defaultValue: 'e1e3c77029759ea7',
			required: true,
		},
		{
			name: 'deviceId',
			type: 'string',
			label: 'Device ID',
			defaultValue: 'e1e3c77029759ea7',
			required: true,
		},
		{
			name: 'status',
			type: 'string',
			label: 'Status',
			defaultValue: 'in_stock',
			required: true,
			description: 'Device status: in_stock or assigned',
		},
		{
			name: 'subId',
			type: 'string',
			label: 'Subscriber ID',
			defaultValue: '',
			required: false,
			description: 'Required when status is assigned',
		},
		{
			name: 'addedDate',
			type: 'string',
			label: 'Added Date',
			defaultValue: new Date().toISOString(),
			required: true,
		},
		{
			name: 'addedBy',
			type: 'string',
			label: 'Added By',
			defaultValue: 'admin',
			required: true,
		},
		{
			name: 'vendorId',
			type: 'string',
			label: 'Vendor ID',
			defaultValue: '',
			required: true,
		},
		{
			name: 'modelNo',
			type: 'string',
			label: 'Model No',
			defaultValue: 'test',
			required: true,
		},
	],
	'assign_package_to_device': [
		{
			name: 'deviceId',
			type: 'string',
			label: 'Device ID',
			defaultValue: 'e1e3c77029759ea6',
			required: true,
		},
		{
			name: 'packages',
			type: 'array',
			label: 'Packages',
			defaultValue: [],
			required: true,
			fields: [
				{
					name: 'packageId',
					type: 'string',
					label: 'Package ID',
					defaultValue: 'aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa',
					required: true,
				},
				{
					name: 'fromDate',
					type: 'number',
					label: 'From Date',
					defaultValue: 0,
					required: true,
					description: 'Current timestamp (will be set to current time)',
				},
				{
					name: 'toDate',
					type: 'number',
					label: 'To Date',
					defaultValue: 0,
					required: true,
					description: 'Next one month timestamp (will be set to current time + 30 days)',
				},
			],
		},
	],
	'renew_package': [
		{
			name: 'deviceId',
			type: 'number',
			label: 'Device ID',
			defaultValue: 1,
			required: true,
		},
		{
			name: 'packageId',
			type: 'number',
			label: 'Package ID',
			defaultValue: 1,
			required: true,
		},
		{
			name: 'extendDays',
			type: 'number',
			label: 'Extend Days',
			defaultValue: 30,
			required: true,
		},
	],
	'renew_subscription': [
		{
			name: 'deviceId',
			type: 'string',
			label: 'Device ID',
			defaultValue: '',
			required: true,
		},
		{
			name: 'packages',
			type: 'array',
			label: 'Packages',
			defaultValue: [],
			required: true,
			fields: [
				{
					name: 'packageId',
					type: 'string',
					label: 'Package ID',
					defaultValue: '',
					required: true,
				},
				{
					name: 'fromDate',
					type: 'number',
					label: 'From Date',
					defaultValue: 0,
					required: true,
				},
				{
					name: 'toDate',
					type: 'number',
					label: 'To Date',
					defaultValue: 0,
					required: true,
				},
			],
		},
	],
	'configure_fingerprint': [
		{
			name: 'type',
			type: 'string',
			label: 'Fingerprint Type',
			defaultValue: 'package',
			required: true,
			description: 'Select fingerprint type',
		},
		{
			name: 'packageIds',
			type: 'array',
			label: 'Package IDs',
			defaultValue: [],
			required: false,
			description: 'Package IDs array (required when type is package)',
		},
		{
			name: 'channelIds',
			type: 'array',
			label: 'Channel IDs',
			defaultValue: [],
			required: false,
			description: 'Channel IDs array (required when type is channel)',
		},
		{
			name: 'deviceIds',
			type: 'array',
			label: 'Device IDs',
			defaultValue: [],
			required: false,
			description: 'Device IDs array (required when type is device)',
		},
		{
			name: 'subscriberIds',
			type: 'array',
			label: 'Subscriber IDs',
			defaultValue: [],
			required: false,
			description: 'Subscriber IDs array (required when type is subscriber)',
		},
	],
	'configure_message': [
		{
			name: 'config',
			type: 'object',
			label: 'Message Configuration',
			defaultValue: {
				enabled: true,
				type: 'notification',
				priority: 'normal',
				expiry: 3600,
			},
			required: true,
			description: 'Message configuration settings',
		},
	],
}
